### ISSUE TITLE
Virtual sound device on Windows Instance

### ISSUE THREAD

**Issue by cmaughan** [actions/virtual-environments#2528]
**Description**  
I'm writing tests for Sonic Pi, using Github Actions.

On Linux I can do 'jackd -d dummy &' to get a virtual audio device.
On Mac, Soundflower is automatically installed (a virtual audio device)
But I'm stuck on Windows. Is there a way for my github action to run a test which finds an audio device on a windows instance? It doesn't need to make a sound, obviously, just register as an audio device that the software can connect to.

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [* ] Windows Server 2016 R2
- [ *] Windows Server 2019

**Expected behavior**  
Some kind of valid sound device is installed

**Actual behavior**  
No sound device is found

**Repro steps**  
Launch an executable as part of an action that requires a sound device (virtual or real).

**Comment by al-cheb** [comment]
Hello, @cmaughan 
Could you please try to install in runtime \[https://github.com/duncanthrax/scream]?

```
jobs:
  compile:
    runs-on: windows-2019
    steps:
      - name: Audio device
        run: Get-CimInstance Win32_SoundDevice | fl *
      - name: Install Scream
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          Extract-7Zip -Path C:\Scream3.6.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream
      - name: Audio device
        run: Get-CimInstance Win32_SoundDevice | fl *
```

![image](https://user-images.githubusercontent.com/47745270/105724100-8e970000-5f38-11eb-85cf-174a537a43ae.png)

**Comment by cmaughan** [comment]
This works great :) Thanks so much for the effort; I hope it didn't take too long!
https://github.com/cmaughan/sonic-pi/runs/1764226203?check_suite_focus=true#step:22:217

**Comment by larsoner** [comment]
@dechamps I use VBCable in the Windows part of sound-ci-helpers (which I use by running `powershell sound-ci-helpers/windows/setup_sound.ps1` on Azure after a clone)

https://github.com/LABSN/sound-ci-helpers

I think it creates an input and an output device, feel free to try it.

I should probably make this a proper GitHub Action step, I don't think it would be too difficult!

**Comment by dechamps** [comment]
On the new `windows-2022` environment (which is currently being rolled out as `windows-latest` - see #4856), workflows using audio devices might break because the Windows Audio engine is not started by default anymore. This can be remedied using the following step:

```yaml
- run: net start audiosrv
```

**Comment by Gustl22** [comment]
@al-cheb can we revive the discussion? Scream cannot afford the certificates, which is more than understandable. GitHub as part of Microsoft may can contribute or support, so that audio testing can become available again on windows:
https://github.com/duncanthrax/scream/issues/202#issuecomment-1649858065
Thank you :)

**Comment by larsoner** [comment]
@Gustl22 it looks like you are talking about driver code signing, whereas this issue is about setting up a virtual sound device on CIs (which does seem possible using two solutions mentioned above: https://github.com/actions/runner-images/issues/2528#issuecomment-1050295010, https://github.com/actions/runner-images/issues/2528#issuecomment-1037547655)

**Comment by Gustl22** [comment]
@larsoner https://github.com/actions/runner-images/issues/2528#issuecomment-1050295010 is no solution (I'm pretty sure at least), it just is an additional step to let Scream add a virtual device, see this [run](https://github.com/bluefireteam/audioplayers/actions/runs/5658232526/job/15329072010). 

And your mentioned action also fails, see this [run](https://github.com/bluefireteam/audioplayers/actions/runs/5658326053/job/15329383736).

Yes, it is not about the specific solution, but it is about a working solution supported by GH Actions.

**Comment by larsoner** [comment]
> And your mentioned action also fails, see this run.

Should be fixed now, feel free to try again :+1: Hopefully it works for now (until GH officially supports something, if ever!)

**Comment by Gustl22** [comment]
Thanks for fixing @larsoner, but even in your solution you propose to use *scream* once, [vb cable driver breaks](https://github.com/LABSN/sound-ci-helpers/blob/254c3f52608593707983fc89c241edc9ea0fe7e9/windows/setup_sound.ps1#L2).
For me, the issue is not solved here.

@al-cheb please reconsider opening again. How does Microsoft solve this problem internally for their tests? Are they using real sound cards for that? Thx.

**Comment by dechamps** [comment]
Looks like the Scream-based solution stopped working at some point on `windows-latest` (`windows-2022 20240514.3.0`) - it hangs on the `devcon` step:

```
Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream

Device node created. Install is complete when drivers are installed...
Updating drivers for *Scream from …\Scream\Install\driver\x64\Scream.inf.
(…hangs forever…)
```

Same if I upgrade to latest Scream 4.0.

Example run: https://github.com/dechamps/FlexASIO/actions/runs/9238174920/job/25415967004

Not sure what broke it?

**Comment by dechamps** [comment]
It took some heroics, but I was able to [capture a screenshot](https://github.com/dechamps/FlexASIO/actions/runs/9242110478):

```yaml
      - shell: powershell
        run: Install-Module -Name PShot -AcceptLicense -Force
      - shell: powershell
        run: |
          Import-Module -Name PShot
          Start-Job { Get-PShot -Directory . -Delay 30 }
          Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream
        continue-on-error: true
        timeout-minutes: 1
      - uses: actions/upload-artifact@v2
        with:
          path: 'PShot*'
```

The result:

![PShot_20240526_091035](https://github.com/actions/runner-images/assets/866859/8ccc44bc-5093-484a-8eae-002c9321d796)

Looks like the `Import-Certificate -FilePath Scream\Install\driver\x64\Scream.cat -CertStoreLocation Cert:\LocalMachine\TrustedPublisher` command is not sufficient for it to work anymore.

**Comment by dechamps** [comment]
And I guess this is why:

![image](https://github.com/actions/runner-images/assets/866859/2c9ba19d-882f-4d65-8ae4-99954df51eec)

I found duncanthrax/scream#215 about this. Looks like it's not going to be fixed, so we're gonna have to find some way to work around this or use a different driver.

**Comment by dechamps** [comment]
…and here's how I worked around it:

```yaml
      - run: 'Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/4.0/Scream4.0.zip -OutFile Scream4.0.zip'
      - run: 'Expand-Archive -Path Scream4.0.zip -DestinationPath Scream'
      # To work around https://github.com/duncanthrax/scream/issues/215, create our own self-signed certificate for the Scream driver.
      # makecert.exe insists on interactively asking the user for a password (sigh...), so use OpenSSL instead.
      # `-extensions v3_req` is a trick to make sure the resulting cert has basic constraint CA:FALSE (the default is CA:TRUE which is problematic here) without having to create an OpenSSL config file.
      - run: 'openssl req -batch -verbose -x509 -newkey rsa -keyout ScreamCertificate.pvk -out ScreamCertificate.cer -nodes -extensions v3_req'
      - run: 'openssl pkcs12 -export -nodes -in ScreamCertificate.cer -inkey ScreamCertificate.pvk -out ScreamCertificate.pfx -passout pass:'
      # This is just to make sure signtool.exe is in the PATH
      - uses: ilammy/msvc-dev-cmd@v1
      # Sign the driver with the self-signed certificate we just made.
      - run: 'signtool sign /v /fd SHA256 /f ScreamCertificate.pfx Scream\Install\driver\x64\Scream.cat'
      # Tell Windows to trust the self-signed certificate we just made.
      # (For some reason it has to be added to both stores for it to work.)
      - run: 'Import-Certificate -FilePath ScreamCertificate.cer -CertStoreLocation Cert:\LocalMachine\root'
      - run: 'Import-Certificate -FilePath ScreamCertificate.cer -CertStoreLocation Cert:\LocalMachine\TrustedPublisher'
      # Finally, install the driver.
      - run: 'Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream'
        # For convenience, make sure we fail fast if for whatever reason the install gets blocked on some GUI prompt.
        timeout-minutes: 5
```

All good now: https://github.com/dechamps/FlexASIO/actions/runs/9242970185/job/25426485555

You'll then likely want to follow that with `net start audiosrv` for the Windows audio stack to actually work.

**Comment by NathanCheshire** [comment]
For anyone trying to do what I was doing, install a virtual sound device on `macos`, `windows`, and `ubuntu` (all `latest`), see [this run](https://github.com/NathanCheshire/CyderUtils/actions/runs/9733272570/job/26859984068) which works for `scream` on `windows` and also the aforementioned as of the date of this comment.
