### ISSUE TITLE
side-by-side NDK installed as the "(obsolete)" NDK

### ISSUE THREAD

**Issue by saurik** [actions/virtual-environments#2689]
Honestly, when reading some of your messages on #2481, I was concerned you were going to think you could do this (lol ;P). The files in the Android SDK are managed by a package manager, and the side-by-side NDK is not exactly the same managed object as the NDK package.

As far as I'm concerned, the correct strategy to is to just *not* install ndk-bundle and instead just install the intended side-by-side NDK for the LTS. Like, I'm pretty sure the NDK package--the one that goes in ndk-bundle--is literally marked as "Obsolete": do we really need it? ;P

This is causing warnings during install of side-by-side packages, but might also (I'm not sure: I was going to finish investigating this today and then type up a better bug report, but I accidentally hit enter on the title field and that apparently caused the issue to submit) be causing errors installing side-by-side NDKs?

Since I'm getting this SSL error also, I'm not sure (and now my mac builds are all just being queued and aren't going through so I can't even test this this morning to try to better isolate what is happening, but I've been getting this install error over the course of three days now).

```
Run echo y | sudo -EH "${ANDROID_HOME}/tools/bin/sdkmanager" "ndk;21.3.6528147" >/dev/null
```
```
Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
Warning: javax.net.ssl.SSLException: readHandshakeRecord
Warning: File /var/root/.android/repositories.cfg could not be loaded.
Warning: Failed to find package ndk;21.3.6528147
Error: Process completed with exit code 1.
```

**Comment by saurik** [comment]
I accidentally hit enter on this before I was done working on the report, which I wasn't expecting to be done with until much later today :(.

**Comment by saurik** [comment]
FWIW, I've been able to get the NDK install to work a few times now (on builders that have the ndk-bundle copy), so I'm betting it is in fact the SSL issue that is actually the thing blocking the ability to install things, and not the inconsistent NDK installation paths. I feel like I've gotten the SSL error a long time ago also, but very rarely (in contrast to now, where it is causing most of--but apparently not all of--my builds to fail).

**Comment by dibir-magomedsaygitov** [comment]
Hello, @saurik, thank for your report. We install 2 versions of NDK (21.x and 22.x) side by side and `ndk-bundle` is the symlink for LTS (21.x) version. Could you please clarify what is the issue and fill up issue with proper description.

**Comment by miketimofeev** [comment]
@saurik I'm going to close the issue since we deployed the images with both the latest NDK (22) and LTS NDK (21) versions. Symlink ndk-bundle points to LTS NDK at the moment.
Please feel free to contact us if you have any concerns.
Thank you!

**Comment by saurik** [comment]
@miketimofeev Yeah, sorry; I've been having it on my todo list to try to figure out why installing the NDK was failing so often, but haven't done so yet (and it does seem to have cleared up, so it might have been some transient issue for those few days that either you fixed or Google fixed). That said, I think it is at least worth noting that merely making ndk-bundle a symlink to a side-by-side installation of the NDK is incorrect from the Android package manager's perspective: it causes those warnings, and build scripts that attempt to work with that ndk-bundle installation using the android tooling... like, think about what happens if you ask the android package manager to upgrade the "NDK (Obsolete)" package to the latest version... is it going to do it into the folder for the LTS NDK side-by-side? (It might not, as it might entirely delete the folder that's there first, but that isn't a given to me seeing the warning they currently are presenting for upgrades of even other packages.) I guess I personally don't see why you would be shipping this symlink at all: that's for a package Google marks "(Obsolete)" anyway.

**Comment by miketimofeev** [comment]
@saurik Thanks for the explanation, we made the symlink to provide backward compatibility for those folks who rely on `ndk-bundle` (there were a lot of them). And it looks like ndk-bundle wasn't marked as obsolete some time ago 🤔 We'll probably revisit this one more time to see what can be done.

**Comment by saurik** [comment]
@dibir-magomedsaygitov @miketimofeev So, this is either still broken or is now broken again after being fixed for a while.

To maybe be more blunt about the issue, as I seem to have fully explained the problem before and yet I was still asked to "clarify": you can't arbitrarily symlink these two folders together and expect the result to work, as the contents of the Android SDK folder isn't some "just so" random collection of files but is instead the result of a package manager carefully installing and managing various versions of packages... like, I'm not sure what mental model you have for this folder which makes it OK to just randomly add a symlink for the ndk-bundle folder to something in the ndk folder, but it isn't shared by the people who wrote the Android SDK manager: if I run sdkmanager and ask it what is installed, it screams in pain--as I showed above--because there's this random symlink behind which the wrong package exists; and if I ask it to uninstall or upgrade the package, I can't, because the package is the wrong package in the wrong place and is malformed due to being a symlink instead of a folder full of files :(.

**Comment by miketimofeev** [comment]
@saurik I agree that the final result produces weird errors but on the other hand, we haven't found any other way to have non-latest ndk as ndk-bundle. If you have any suggestions, please share them as our team doesn't have much experience in Android development.

**Comment by saurik** [comment]
@miketimofeev If that's your goal -- and I want to be explicit that I do not agree with this goal, as ndk-bundle was explicitly marked as "Obsolete" by Google years ago and is no longer even something Android Studio shows as installable unless you go out of your way to uncheck "Hide Obsolete Packages" (which I doubt many people do), and so I maintain you should NOT be attempting to do anything with ndk-bundle as no one should be using it anymore -- then you need to put a package called ndk-bundle in the ndk-bundle folder that has a package.xml with the correct package name but with the older version number so the package manager knows what is there and can manage it correctly. This isn't really an "Android development" issue but is more of a "how package managers work" issue :(.

**Comment by miketimofeev** [comment]
@saurik thanks for all the suggestions and such a detailed explanation. We haven't noticed that ndk-bundle is obsolete for a while so it might be a better solution to announce its deprecation from the images and remove all those weird symlinks after all. We will investigate the possible impact and prepare an announcement.

**Comment by MarijnS95** [comment]
Could this have possibly kept `export ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME` for the vast majority of users who probably want "some" (typically close to the latest) NDK but most likely don't care about the exact version, to minimize breakage caused by "fixing" this?
