### ISSUE TITLE
[macOS] Default Xcode on Monterey image will be set to Xcode 13.3 on April, 4

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#5328]
### Breaking changes

Default Xcode will be changed to 13.3 on macOS 12.3 Monterey. Xamarin bundle will also be changed to the latest one that supports Xcode 13.3

### Target date

Update propagation will start on April, 4 and will take 3-4 days.

### The motivation for the changes

We would like to provide images with the latest stable updates as default ones.

### Possible impact

If you use the default Xcode version and your project is not compatible with Xcode 13.3 your build can be broken.
If your project is not compatible with the latest Xamarin bundle it can be broken.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [x] macOS 12
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Please consider switching Xcode in runtime to the version that you need to build an app.
The following snippet can be used to switch Xcode:
```bash
sudo xcode-select -s "/Applications/Xcode_13.2.1.app"
```
The list of all available Xcode versions can be found in the [image documentation](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode)

You can also select any Xamarin version by running
```bash
XAMARIN_SDK=6_12_7
$VM_ASSETS/select-xamarin-sdk.sh $XAMARIN_SDK
```
The list of all available Xamarin bundles can be found in the [image documentation](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xamarin-bundles)

**Comment by eschwieb** [comment]
That should be "macOS 12.3 Monterey" in the first line.

**Comment by mrgrauel** [comment]
Is there a problem with the upgrade? All our jobs which should run on `macos-12` are queued since yesterday.

> Requested labels: macos-12
Job defined at: ...path...
Waiting for a runner to pick up this job...

**Comment by miketimofeev** [comment]
@mrgrauel we're investigating it at the moment

**Comment by eseay** [comment]
> @mrgrauel we're investigating it at the moment

@mrgrauel Any update here? We're trying to figure out how to proceed since all of our workflows are hard-blocked.

**Comment by miketimofeev** [comment]
@mrgrauel @eseay could you try running new ones? The issue should be fixed

**Comment by eseay** [comment]
@miketimofeev Looks like we're back online. Thanks! Will keep you posted if things change.

**Comment by mrgrauel** [comment]
@miketimofeev looks good 👍 Thank you

**Comment by james-barker-sedgwick** [comment]
This issue still occurs for the project I am working on.

##Error
```
##[warning]An image label with the label macOS-12 does not exist.
,##[error]The remote provider was unable to process the request.
Pool: [Azure Pipelines](https://dev.azure.com/***/***/_settings/agentqueues?poolId=&queueId=***)
Image: macOS-12
Started: 2022-04-06 at 3:33 PM CDT
```

## Pipline YAML
```
- job: iOS
  pool:
      vmImage: 'macOS-12'
```

**Comment by niehusstaab** [comment]
> Pipline YAML
> 
> ```
> - job: iOS
>   pool:
>       vmImage: 'macOS-12'
> ```

I could be wrong, but I think you've got a typo: should be `macos-12` not `macOS-12`

**Comment by james-barker-sedgwick** [comment]
> 

We tried that as well. Same issue.

**Comment by miketimofeev** [comment]
@james-barker-sedgwick Azure DevOps is not provisioned with macOS-12 yet.

**Comment by foxsin10** [comment]
Any update? [5338](https://github.com/actions/virtual-environments/pull/5338) merged, but action still will be queued when running on macos-12.

**Comment by miketimofeev** [comment]
@foxsin10 have you submitted the access request?

**Comment by foxsin10** [comment]
@miketimofeev thanks for responding.
Our GitHub Action will be queued, if set the `runs-on` to `macos-12` as @mrgrauel mentioned.
As for the `access request`, if i need to submit an access request to use `macos-12`, could you tell me how, thanks.

**Comment by miketimofeev** [comment]
@foxsin10 Please [complete this form](https://forms.gle/D1ihWjw3xDfjYbu67) In order to request access to the macOS 12 private beta. Once your request has been reviewed, we'll send an email confirming access has been provided with instructions for how to utilize the image in your workflows.

**Comment by miketimofeev** [comment]
The changes are now deployed

**Comment by bnidevs** [comment]
@miketimofeev what's the turnaround time on filling out the form? just curious, thanks.

**Comment by jonas-simkus-mw** [comment]
Any reason why `macos-12` not mentioned in here https://github.com/actions/virtual-environments ?  
Maybe it's not supported yet?

**Comment by miketimofeev** [comment]
@bnidevs we onboard users weekly.
@jonas-simkus-mw we do not mention the image until it is in private preview.

**Comment by bnidevs** [comment]
thank you @miketimofeev

**Comment by mattiacantalu** [comment]
> @bnidevs we onboard users weekly. @jonas-simkus-mw we do not mention the image until it is in private preview.

Do you have an ETA for the public release?
