### ISSUE TITLE
[Azure DevOps] Windows-2016 environment removal postponed until July 31, 2022

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#5403]
### Breaking changes

Windows 2016 hosted runners were scheduled for full removal on April 1, 2022. However, we are still seeing significant usage from customers and we want to give them more time to migrate to the new runners. In order to give customers another chance to move to either windows-2019 or windows-2022 we will delay the removal of windows-2016 until July 31, 2022.

To raise awareness of the removal, we will have rolling 24-hour periods where the image will be unavailable for customers. During these "brownout" periods, customers will see an error message indicating that the image is slated for removal on July 31, 2022. The schedule for those brownout periods is as follows for Azure DevOps:

- Monday April 18, 00:00 UTC to April 19, 00:00 UTC
- Tuesday April 26, 00:00 UTC to April 27, 00:00 UTC
- Wednesday May 4, 00:00 UTC to May 5, 00:00 UTC
- Thursday May 12, 00:00 UTC to May 13, 00:00 UTC
- Friday May 20, 00:00 UTC to May 21, 00:00 UTC
- Monday May 23, 00:00 UTC to May 24, 00:00 UTC
- Tuesday May 31, 00:00 UTC to June 1, 00:00 UTC
- Wednesday June 8, 00:00 UTC to June 9, 00:00 UTC
- Thursday June 16, 00:00 UTC to June 17, 00:00 UTC
- Friday June 24, 00:00 UTC to June 25, 00:00 UTC
- Monday June 27, 00:00 UTC to June 28, 00:00 UTC
- Friday July 22, 00:00 UTC to July 23, 00:00 UTC
- Wednesday July 27, 00:00 UTC to July 28, 00:00 UTC
- Full removal - July 31, 15:00 UTC

See the original announcement at https://github.com/actions/virtual-environments/issues/4312

### Target date

July 31, 2022

### The motivation for the changes

Windows Server 2016 Active support ends on 11 Jan 2022 and Windows Server 2022 VM image is going out of beta later this year.
As part of our ongoing efforts to keep GitHub and Azure Devops hosted runners updated and secure, the Windows 2016 virtual environment will be removed from GitHub Actions and Azure DevOps.

### Possible impact

Workflows targeting the Windows 2016 image will fail.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [x] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Change your workflows to use windows-latest, windows-2022, or windows-2019

**Comment by kningyi** [comment]
Noob here, our yml config is already using `vmImage: 'windows-latest'` but we're still seeing the error. What should we do?

![image](https://user-images.githubusercontent.com/13121503/164146567-b70e6072-a3b5-468f-8a84-354298cc046a.png)
![image](https://user-images.githubusercontent.com/13121503/164146636-08b9d113-e5c9-4271-91e1-72ccb99447e9.png)

**Comment by miketimofeev** [comment]
@kningyi please remove everything below the 
```
pool:
    vmImage: 'windows-latest'
```
and you should be good to go

**Comment by Aeroverra** [comment]
I have a release pipeline (the one in the Releases tab) that gets triggered after a pipeline from the Pipelines Tab that I use for deployment to azure.  This deployment keeps failing because of the 2016 error. 

In the normal build pipeline I was able to set the vmImage but I don't see any way to access the yaml or change the image in the release pipeline edit page. How can this be done? I have tried searching this up plenty of times with no luck. 

Also when you make a release pipeline why does it default to 2016? My guess would be the reason you are seeing so many people still using 2016 is because its still the default when you make a new pipeline and not so much that people are targeting it.

**Comment by slonopotamus** [comment]
> As part of our ongoing efforts to keep GitHub and Azure Devops hosted runners *updated and secure*

Isn't Windows Server 2016 going to get security updates until 2027 and this "motivation" is simply misleading?

**Comment by eli-schwartz** [comment]
As discussed in #5238

> During these "brownout" periods, customers will see an error message indicating that the image is slated for removal on June 30, 2022.

The brownout error message still says April 1 and points to an old ticket with out-of-date information.

**Comment by robertoandrade** [comment]
> > As part of our ongoing efforts to keep GitHub and Azure Devops hosted runners _updated and secure_
> 
> Isn't Windows Server 2016 going to get security updates until 2027 and this "motivation" is simply misleading?

I agree 100% with this. According to [Microsoft's own documentation](https://docs.microsoft.com/en-us/lifecycle/end-of-support/end-of-support-2027), Windows Server 2016 will continue to get security updates until Jan 12, 2027 when it will finally stop receiving it which would justify for Microsoft to remove support for it on pipelines or start these brownouts.

**Comment by afelthe** [comment]
I keep getting this error in my release pipelines and cannot figure out where to go to fix it.  I am not using YAML but CLI.

**Comment by mohitook** [comment]
I get this message the whole day. Could you move your maintenance window out of work-hours next time? We'd appreciate it.
![image](https://user-images.githubusercontent.com/15103326/168066802-ba1e666e-a677-4fe5-8617-796d51004fef.png)

Additionally our systems are not using any windows-2016 related element, so the error itself makes no sense...

**Comment by miketimofeev** [comment]
@mohitook if the systems don't use then you won't see the message. Maybe some of you jobs are using windows-2016 as it was the default image some time ago?

**Comment by carvido1** [comment]
Hello.
Is this affecting also self hosted runners ? It is not clear to me

**Comment by miketimofeev** [comment]
@carvido1 no, it is not

**Comment by sicklittlemonkey** [comment]
> @mohitook if the systems don't use then you won't see the message. Maybe some of your jobs are using windows-2016 as it was the default image some time ago?

Yep, for me it was a copy of an older pipeline. I thought the error was just for the pipeline being run, but it seems to be caused by *any other 2016 agent setting you have*.

**Comment by bobblybit** [comment]
how do i fix this issue [](url
![issues](https://user-images.githubusercontent.com/55890407/174121119-bf58c766-3d72-4990-bf38-afe48d50c515.PNG)
)

**Comment by bobblybit** [comment]
> @mohitook if the systems don't use then you won't see the message. Maybe some of your jobs are using windows-2016 as it was the default image some time ago?
![issues](https://user-images.githubusercontent.com/55890407/174121354-3a040d14-0e74-4c0d-948a-7c8f0d329227.PNG)

please how  do i fix this

**Comment by angiurgiu** [comment]
One of our build steps is getting this brownout error, however I can't find what's still using WIN2016. I've looked at all the YAMLs. @miketimofeev 

https://skype.visualstudio.com/SCC/_releaseProgress?_a=release-environment-logs&releaseId=567067&environmentId=6245439

**Comment by megamingus** [comment]
Hey, I was just hit by the brownout in a pipeline working flawlessly for years 😭.
I'm not sure but, it seems that there are missing some UWP SDKs?

```##
##[warning]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\WindowsXaml\v17.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets(676,5): Warning : Could not find target platform winmds for the SDK specified by [Windows, 10.0, UAP, 10.0.10240.0, 10.0.15063.0]
##[debug]Processed: ##vso[task.logissue type=Warning;sourcepath=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\WindowsXaml\v17.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets;linenumber=676;columnnumber=5;code=;]Could not find target platform winmds for the SDK specified by [Windows, 10.0, UAP, 10.0.10240.0, 10.0.15063.0]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\WindowsXaml\v17.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets(676,5): warning : Could not find target platform winmds for the SDK specified by [Windows, 10.0, UAP, 10.0.10240.0, 10.0.15063.0] 
[...]
##[error]MuralSketch.Core\Components\InkAnalyzerComponent\InkAnalyzerComponentModel.cs(7,31): Error CS0234: The type or namespace name 'Analysis' does not exist in the namespace 'Windows.UI.Input.Inking' (are you missing an assembly reference?)
```

**Comment by gsmtcnr** [comment]
![image](https://user-images.githubusercontent.com/31734521/176022000-112cfa2c-9d49-462d-bb8d-69688acc968b.png)

I selected windows2022 instead of vs2017-win2016 then It fixed.

**Comment by JMA-Dv** [comment]
I made a post in stack where I explaned how I fixed this issue. If you're interested
`https://stackoverflow.com/questions/71493785/error-deploying-release-pipeline-windows-2016-deprecated-azure-devops/72779265#72779265`

**Comment by kapilvagyani** [comment]
Does this means after 30th June 2022  we wont be able to create VM even for window server **sku- "2016-Datacenter-Server-Core"** using images from Microsoft market place ?
pls clarify. Thanks in advance. Kapil

**Comment by megamingus** [comment]
is there a way to install missing UWP SDKs in newer images? or are te images going to be updated with the missing ones?

**Comment by miketimofeev** [comment]
@megamingus what SDKs do you mean?

**Comment by melchiorbc** [comment]
Hello, in our organization we still see jobs being run on Microsoft Hosted vs2017-win2016 Agents. I thought these would no longer be available as of 30 June? When can we expect these to be offline permanently?

**Comment by miketimofeev** [comment]
@melchiorbc we are a bit delayed with some changes to default hosted images. Most likely the image will be fully deprecated in 1-2 weeks.

**Comment by rushfrisby** [comment]
What other agent can build .NET Framework projects? I've tried windows-latest, windows-2022, and windows-2019 but the solution fails to build on all with an error about not being able to locate the .NET Framework assemblies.

**Comment by miketimofeev** [comment]
@rushfrisby what error do you have? Windows-2019, for example, has a reduced set of installed .Net frameworks:
`4.7.2 & 4.8` vs `4.6.1, 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8` on windows-2016

**Comment by al-cheb** [comment]
@rushfrisby, Could you bump .Net version to 4.6.2?

**Comment by JMA-Dv** [comment]
@rushfrisby  I ran against this issue.
1) Try to point your project to .NET v4.8. 
2) Re-publish now with the v4.8 project. (if it doesn't fix it, go to step 3).
3) In your .yaml pipeline check for the pool tag. and change the vmImage: 'windows-2016' to 'windows-2019' or 'windows-latest'
4) Re-run your pipeline.

Those were my steps to correct the issue.

**Comment by DeeDeeG** [comment]
We have a project that started experiencing CI errors in the new image, even when we installed older Visual Studio Build Tools with Chocolatey. So newer Visual Studio isn't the culprit. https://github.com/atom-community/atom/issues/428

Does anyone have any idea what else is different about the new CI image environment that would have caused this? _(Other than Visual Studio being newer?)_ Any hints of where to zero in our troubleshooting? Thank you.

**Comment by miketimofeev** [comment]
The new retirement date is set — July, 22

**Comment by miketimofeev** [comment]
The retirement date is shifted to July, 31

**Comment by melchiorbc** [comment]
LOL, can you guys please, please, please stop shifting the retirement date :) every time we need to tell our developers to stop using Win2016 as Agent type, and each time you guys postpone the deadline slowly people start using it again (I know their own fault), and we need to start warning them again, but we (and also Microsoft) are loosing our credibility on when they are actually decommissioned.

**Comment by miketimofeev** [comment]
@melchiorbc sorry for the inconvenience, hopefully, this is the last one 🤞

**Comment by miketimofeev** [comment]
Two more brownout dates are set:
- Friday July 22, 00:00 UTC to July 23, 00:00 UTC
- Wednesday July 27, 00:00 UTC to July 28, 00:00 UTC

**Comment by miketimofeev** [comment]
Windows 2016 environment is finally deprecated in ADO.

**Comment by ddeveza** [comment]
![image](https://user-images.githubusercontent.com/13481326/183816823-934a5d2a-d403-4ab7-8d01-568ade071a4d.png)
I already updated the agent spec but still encountering the error of 2016 deprecation.
![image](https://user-images.githubusercontent.com/13481326/183816948-a6056bb8-2075-414d-b4d2-46bc3bd27489.png)

**Comment by Bondarenko1990** [comment]
> Windows 2016 hosted runners were scheduled for full removal on April 1, 2022. However, we are still seeing significant usage from customers and we want to give them more time to migrate to the new runners. In order to give customers another chance to move to either windows-2019 or windows-2022 we will delay the removal of windows-2016 until July 31, 2022.

same error. I use windows-2019

**Comment by melchiorbc** [comment]
> Windows 2016 environment is finally deprecated in ADO.

Hi Mike, are you sure of this? Up to today we still see jobs using the "vs2017-win2016" Microsoft Hosted Agent image.

**Comment by miketimofeev** [comment]
@melchiorbc could you share a few links, please? I don't need access to pipelines, will take a look at telemetry by those urls

**Comment by melchiorbc** [comment]
@miketimofeev I checked and I do see now the jobs trying to use 'vs2017-win2016' do get cancelled by Microsoft stating this is a deprecated environment, only people are still able to pick the 'vs2017-win2016' in their pipelines from the dropdown with VM types (which is confusing).
![image](https://user-images.githubusercontent.com/45199629/186115734-4964bb82-5bc2-42fa-b0bf-29c949172cad.png)

**Comment by miketimofeev** [comment]
@melchiorbc this is fixed now, sorry for the inconvenience
