### ISSUE TITLE
Screen Resolution Utility gives error on MS-Hosted agents

### ISSUE THREAD

**Issue by ralucapredacegeka** [actions/virtual-environments#629]
**Describe the bug**
Microsoft hosted agent(Azure Pipelines) started giving this error:  
##[warning]The current user session is not a console session. It may not be possible to change the screen resolution. Please ensure that agent is running with autologon and disconnect any remote desktop sessions. 
##[error]Failed to change the resolution.  
We are using agent specification vs2017-win2016 but were able to reproduce it on windows-2019 as well.  We want to change the specific screen resolution to 1920x1080.

**Area for Triage**: Servers

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by jcageman** [comment]
Some additional information that might help resolving the issue faster (received from a user of Screen Resolution Utility website below):

Tracking it out, based on the source code of the ScreenResolutionUtility.ps1 the utility is just calling the win32 function user32.dll ChangeDisplaySettings

This has been acked by microsoft:
Ack, we are able to repro this. It seems to be an issue with the latest set of hosted images. Can you please file an issue at https://github.com/actions/virtual-environments

Source:
https://marketplace.visualstudio.com/items?itemName=ms-autotest.screen-resolution-utility-task&ssr=false#qna

**Comment by jstoppa** [comment]
we are having the same issue and I suppose anyone that uses hosted agent. did you find any work around for the time being?

**Comment by ralucapredacegeka** [comment]
Hi! When can we expect a solution or a workaround for this one? Our releases/tests have been failing for almost a week know.

**Comment by nesshoever** [comment]
Or maybe any workaround ti get a different resolution than the default 1028x768 (other than setting up a VM manually ;) )

**Comment by bartchojnacki** [comment]
It seems that the issue returned last night (UK) - it was working fine over the weekend

"2020-03-31T08:12:54.7286667Z ##[warning]The current user session is not a console session. It may not be possible to change the screen resolution. Please ensure that agent is running with autologon and disconnect any remote desktop sessions."

**Comment by alepauly** [comment]
@bartchojnacki @nesshoever @ralucapredacegeka @jcageman Apologies for the disruption. We are rolling out a fix, should be everywhere within the next two days.

As @bartchojnacki experienced, it is possible for successes to happen while the fix is completely rolled out.

**Comment by ralucapredacegeka** [comment]
Hi @alepauly ! Please be aware that we are still facing this issue on both vs2017-win2016

**Comment by lonevvolf** [comment]
We still have the issue - has it been completely rolled out?

**Comment by GhassanDukes** [comment]
As lonevvolf we are still seeing the same issue. Is there any ETA for when this will be fully rolled out?

**Comment by rsemenov** [comment]
👋 Unfortunately, we had to revert the fix we made last week as it revealed another more serious issue. At this time we fixed both issues and starting the rollout today and will rollout faster than regular release. It should reach all customers by Tuesday. We apologize for the inconvenience this has caused.

**Comment by GhassanDukes** [comment]
@rsemenov thank you for the update. By Tuesday, do you mean 7th April? Or next Tue 14th April?

**Comment by rsemenov** [comment]
We will try our best to rollout by April 7.

**Comment by chiranjeevi5850** [comment]
Is there any update.
when can we expect.

**Comment by saurabhchanchawat** [comment]
Still facing same issue for both vs2017-win2016 & windows-2019.
Agent version - 2.165.2
Is the rollout completed or still in progress?

**Comment by rsemenov** [comment]
The rollout supposed the be completed today but we hit at another issue on the last ring and had to rollback. We are verifying the fix to the new issue and will try the rollout tomorrow.

**Comment by Automobileservices4** [comment]
#629

**Comment by rsemenov** [comment]
The fix is partially available at this point and we finishing rolling it out to the last ring. It should be on everywhere tomorrow.

**Comment by raul70** [comment]
It's still not working on windows-2019 hosted agents. The same warning & errors are displayed.

**Comment by post2vishwa** [comment]
Hi Ruslan,

Good day!

Could you confirm on fix is rolled out everywhere? 

Thanks,
Vishwa

**Comment by post2vishwa** [comment]
> The fix is partially available at this point and we finishing rolling it out to the last ring. It should be on everywhere tomorrow.

Hi Ruslan,

Good day!

Could you confirm on fix is rolled out everywhere?

Thanks,
Vishwa

**Comment by TrickTester** [comment]
Great. Issue is resolved.

**Comment by TrickTester** [comment]
Issue is resolved but I am seeing one odd error as some of the agent has this pop up open which is blocking my selenium test.

![image](https://user-images.githubusercontent.com/18321998/79222318-efa38a80-7e74-11ea-885c-a2e21b17874d.png)

**Comment by rsemenov** [comment]
The fix for this issue has been rolled out everywhere since Friday evening.

**Comment by miketimofeev** [comment]
@ralucapredacegeka I'm going to close the issue, but feel free to reopen if you have any concerns.
Thank you!

**Comment by jithinjosejacob** [comment]
@miketimofeev - can you please let me know the package version for this update,i am facing the same issue and have limited access to the machine,and need to provide IT Team with the above details

**Comment by miketimofeev** [comment]
Sorry, @jithinjosejacob what do you mean by package version?

**Comment by jithinjosejacob** [comment]
The agent version which has the above fix

**Comment by miketimofeev** [comment]
@jithinjosejacob I'm afraid it's not connected with agent version, it's some kind of VM provisioner, which version isn't shown anywhere.
Do you have the exact same issue? You can try one of the methods described here to debug it
https://github.com/actions/virtual-environments/issues/924

**Comment by sean-redmond** [comment]
@rsemenov - Can I ask what the fix was that you rolled out? I am hitting the same error with some self hosted agents I built using the packer scripts from here.

**Comment by rsemenov** [comment]
@sean-redmond , the fix was to run the agent in an interactive session. To do that we had to register a scheduled task for the agent and manually start it. Make sure that after the agent is started as scheduled task it runs with administrator permissions.

**Comment by sean-redmond** [comment]
Thanks, thats really useful, did you publish the changes anywhere?

**Comment by rsemenov** [comment]
@sean-redmond, These changes were internal to a non-opensource component of our system.

**Comment by chilakamarthi** [comment]
I still see the issue when I try to run the pipeline in Azure Cloud VM.

`Starting: Set Resolution of Remote machine
==============================================================================
Task         : Screen Resolution Utility
Description  : Set the screen resolution of the agent machine. Useful when running UI tests.
Version      : 1.0.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=865425)
==============================================================================
##[warning]The current user session is not a console session. It may not be possible to change the screen resolution. Please ensure that agent is running with autologon and disconnect any remote desktop sessions.
##[error]Failed to change the resolution.
Finishing: Set Resolution of Remote machine`

**Comment by james1301** [comment]
I am getting this issue too.
