### ISSUE TITLE
Unable to connect to azure.archive.ubuntu.com flaky failure on ubuntu-latest

### ISSUE THREAD

**Issue by traversaro** [actions/virtual-environments#675]
**Describe the bug**
On some jobs (apparently in a non-deterministic way) commands such as `apt-get install` fail with the following error: 
~~~
Get:1 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 gdb amd64 8.2-0ubuntu1~18.04 [3024 kB]
Get:2 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 gdbserver amd64 8.2-0ubuntu1~18.04 [292 kB]
Get:3 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libxml2-dev amd64 2.9.10+dfsg-2+ubuntu18.04.1+deb.sury.org+1 [821 kB]
Get:4 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libxml2 amd64 2.9.10+dfsg-2+ubuntu18.04.1+deb.sury.org+1 [726 kB]
Get:5 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libgraphicsmagick-q16-3 amd64 1.3.30+hg15796-1+ubuntu18.04.1+deb.sury.org+2 [1181 kB]
Get:6 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libgraphicsmagick++-q16-12 amd64 1.3.30+hg15796-1+ubuntu18.04.1+deb.sury.org+2 [144 kB]
Err:7 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libdouble-conversion1 amd64 2.0.1-4ubuntu1
  Could not connect to azure.archive.ubuntu.com:80 (52.177.174.250), connection timed out
Ign:8 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libqt5core5a amd64 5.9.5+dfsg-0ubuntu2.5
Ign:9 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libwayland-server0 amd64 1.16.0-1ubuntu1.1~18.04.3
Err:10 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgbm1 amd64 19.2.8-0ubuntu0~18.04.3
  Unable to connect to azure.archive.ubuntu.com:http:
Err:11 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-xfixes0 amd64 1.13-2~ubuntu18.04
  Unable to connect to azure.archive.ubuntu.com:http:
Err:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libegl-mesa0 amd64 19.2.8-0ubuntu0~18.04.3
  Unable to connect to azure.archive.ubuntu.com:http:
Err:13 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libegl1 amd64 1.0.0-2ubuntu2.3
~~~

For an example of such failure, check https://github.com/robotology/idyntree/pull/668/checks?check_run_id=560084383 . I would not be too  surprised about CI jobs failing for networks problems, but this specific issue seems to be extremely frequent. I did not collect precise data on how much frequently this happens, but my impression that it happens in the order of magnitude of 1 out of 10 builds.

This issue is already being discussed on GitHub Community Forum at https://github.community/t5/GitHub-Actions/Install-dependencies-in-Ubuntu-flakes-several-times-a-wekk/td-p/51785 , but the GitHub support suggested me to open  an issue here as well.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug 

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
I would expect commands such as `apt-get install` to work correctly. 

**Actual behavior**
It is not clear what is triggering this behavior, but sometimes `apt-get install`  fails.

**Comment by MSP-Greg** [comment]
I added `-o Acquire::Retries=3`, and today it worked, then failed for a while, then starting working again.

It may not be a GitHub issue, but they (and especially MSFT) have the resources to mirror azure.archive.ubuntu.com so Actions CI is reliable...

**Comment by boegel** [comment]
We've been seeing issues like this fairly frequently since Sunday March 29th...

**Comment by boegel** [comment]
Using `-o Acquire::Retries=3` is not helping for us, see for example https://github.com/easybuilders/easybuild-easyblocks/pull/2012/checks?check_run_id=563883264

**Comment by MCOfficer** [comment]
I mentioned this on the github community post, but you can probably use [apt-spy2](https://github.com/lagged/apt-spy2) to find a working mirror before using apt.

**Comment by MSP-Greg** [comment]
@boegel 

Sorry, I didn't mean to imply that using `-o Acquire::Retries=3` was a fix.  What I meant was that if one is using it and `apt-get` still times out, there is really a problem.

**Comment by boegel** [comment]
> I mentioned this on the github community post, but you can probably use [apt-spy2](https://github.com/lagged/apt-spy2) to find a working mirror before using apt.

That adds a couple of minutes to each run, but it seems to work well to circumvent the problems, thanks a lot!

For other, see for example https://github.com/easybuilders/easybuild-easyconfigs/pull/10341

**Comment by znarf** [comment]
On our side, we get `503` errors on almost all runs past few hours:

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/f/fonts-arphic-bkai00mp/fonts-arphic-bkai00mp_2.10-17_all.deb  503  Service Unavailable [IP: 52.177.174.250 80]
```

**Comment by Automobileservices4** [comment]
#675

**Comment by deivid-rodriguez** [comment]
I added this to my workflow before `apt-get install` as a workaround:

```bash
sudo sed -i 's/azure\.//' /etc/apt/sources.list
sudo apt-get update
```

**Comment by paoloczi** [comment]
Several workarounds proposed, but no comments about fixing this for real. This is a serious issue making GitHub Actions unusable for anybody working with Ubuntu, and should be looked at with high priority.

**Comment by Automobileservices4** [comment]
Automobileengineeringservices

Kyaw

**Comment by alepauly** [comment]
@traversaro (and everyone else affected) - We've engaged the mirror hosts and they have added capacity to improve it's reliability. I'll keep this open until we can confirm the issue is resolved. Please let us know if this continues to occur. Thank you for the reports.

**Comment by MSP-Greg** [comment]
@alepauly

Thank you.

Last saw a problem at 23:15 GMT (3 hours ago), at which point I changed servers.  Did the update/change happen after that?

**Comment by alepauly** [comment]
@MSP-Greg, I don't have he exact time where the fixes were put in place yet but I believe it was in the last two hours. Please let me know if you see more issues, thanks!

**Comment by traversaro** [comment]
> @traversaro (and everyone else affected) - We've engaged the mirror hosts and they have added capacity to improve its reliability. I'll keep this open until we can confirm the issue is resolved. Please let us know if this continues to occur. Thank you for the reports.

Thanks a lot @alepauly !

**Comment by hloeung** [comment]
@alepauly has something changed with GitHub's Actions on the 24th March?

**Comment by alepauly** [comment]
> @alepauly has something changed with GitHub's Actions on the 24th March?

@hloeung we make improvements constantly so, yes. If you're having a specific problem with the tools installed please file an issue in this repo so we can help.

**Comment by pestophagous** [comment]
Noting another workaround, since there are many interested parties on this thread:

https://github.com/ros2/rmw_cyclonedds/pull/134/files

I'm not the author of that, but I found it a few days ago when I saw this azure-related outage was happening to me. I took the same approach as the ros2/rmw_cyclonedds team, and I've been quite happy with it.

Based on search results I found on April 1 (before this present issue #675 had been created), this is a recurring problem: https://github.community/t5/GitHub-Actions/sudo-apt-install-fails-with-Unable-to-connect-to-azure-archive/td-p/32154

**Comment by hloeung** [comment]
@alepauly how can I get in touch with you? Would like to discuss something without having to file an issue.

**Comment by boegel** [comment]
We changed to using `apt-spy2` a couple of days ago which helped for a while, but today tests starting failing again because of what looks like a faulty mirror picked by `apt-spy2`:

```
E: Failed to fetch http://mirrors.codec-cluster.org/ubuntu/pool/universe/l/lua-bit32/lua-bit32_5.3.0-3_amd64.deb  403  Forbidden [IP: 65.49.71.107 80]
```

So, we've disabled the use of `apt-spy2` again, based on @alepauly's comment that the issues with `azure.archive.ubuntu.com` should be largely resolved now... (see https://github.com/easybuilders/easybuild-easyconfigs/pull/10374)

**Comment by traversaro** [comment]
It is not an extensive test, but personally I did not have any more azure.archive.ubuntu.com-related failures in the last few days, thanks @alepauly .

**Comment by deivid-rodriguez** [comment]
Neither did us, everything seems fine now :+1:.

**Comment by miketimofeev** [comment]
@traversaro @deivid-rodriguez thanks for the updates! We're going to close the issue, but feel free to open a new one if there are any similar issues in the future.

**Comment by akhilerm** [comment]
Hitting the same issue in ubuntu bionic. when running 
`apt-get install`
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_237-3ubuntu10.41_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by MCOfficer** [comment]
Not the same issue - the mirror is reachable, but doesn't have the file you request. Did you run `apt-get update`?

**Comment by akhilerm** [comment]
@MCOfficer Was the package recently removed from `azure.ubuntu.com` ? Because it was working till yesterday.

Yep. its working after doing `apt-get update`

**Comment by MCOfficer** [comment]
> 
> 
> @MCOfficer Was the package recently removed from `azure.ubuntu.com` ? Because it was working till yesterday.
> 

When a package is updated, the old version may be removed from the mirror. If you get  404's, 99% of the time `apt-get update` fixes it by fetching the mirror's new index.

**Comment by jessevdp** [comment]
I can confirm that running `apt-get update` before any calls to `apt-get install` on GitHub Actions seems to resolve this issue. We started experiencing this problem just today.

**Comment by username1565** [comment]
I see this issue, about azure-pipeline.

I see the following pathway: 
http://azure.archive.ubuntu.com/ubuntu/ubuntu/ 
`/ubuntu/ubuntu/`. Maybe you can fix this, on the server-side, or help to fix.
Because I do not know how to contact admin of that server.

**Comment by hloeung** [comment]
> I see this issue, about azure-pipeline.
> 
> I see the following pathway:
> http://azure.archive.ubuntu.com/ubuntu/ubuntu/
> `/ubuntu/ubuntu/`. Maybe you can fix this, on the server-side, or help to fix.
> Because I do not know how to contact admin of that server.

What is the issue here? The /ubuntu symlink to . is there by design for those hosting community mirrors where the ubuntu mirror isn't exactly under / or /ubuntu. It's also the same on the main Ubuntu archive mirrors, e.g. http://archive.ubuntu.com/ubuntu/ubuntu/ubuntu/ubuntu/

**Comment by XVilka** [comment]
Still happens: https://github.com/rizinorg/rz-ghidra/runs/3398556746?check_suite_focus=true#step:6:110
```
Current runner version: '2.280.3'
Operating System
  Ubuntu
  20.04.2
  LTS
...
Run sudo apt-get install ninja-build libgraphviz-dev bison flex qt5-default
...
Fetched 18.6 MB in 0s (61.0 MB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_21.0.3-0ubuntu0.2~20.04.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by catthehacker** [comment]
@XVilka you need to run `apt-get update` before `apt-get install`

**Comment by Cireo** [comment]
This is still happening often enough to notice, at this very moment, last week, in January, and late last year.

**Comment by Stratus3D** [comment]
Still happening - https://github.com/asdf-vm/asdf-erlang/pull/245

**Comment by hloeung** [comment]
Maybe GitHub hosted runners should run or have "apt-get update" built into ubuntu-latest.

**Comment by Cireo** [comment]
@catthehacker it is true you need to run `update` before `install`, and some people may see similar symptoms by failing to do so, but this is a real bug that occurs with steps that are nothing more than
```
sudo apt update
sudo apt -y install <package>
```

**Comment by catthehacker** [comment]
> but this is a real bug that occurs with steps that are nothing more than

yes? If you have issues with connection timing out then it is an issue described here.
My comment was for the person that thought they had same issue. I have no idea what do you mean and why I was pinged.

> the timing window can be exacerbated if the script has multiple apt install commands in a row

specify multiple packages in a single `apt-get install` command then

**Comment by muralidar44** [comment]
i still face same issue, sudo apt-get update itself doesnt work

**Comment by neilyoung** [comment]
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/libgstreamer-plugins-base1.0-0_1.16.3-0ubuntu1_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-plugins-base_1.16.3-0ubuntu1_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.

```

**Comment by MCOfficer** [comment]
> ```
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/libgstreamer-plugins-base1.0-0_1.16.3-0ubuntu1_amd64.deb[](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/libgstreamer-plugins-base1.0-0_1.16.3-0ubuntu1_amd64.deb)  404  Not Found [IP: 20.106.104.242 80]
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-plugins-base_1.16.3-0ubuntu1_amd64.deb[](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-plugins-base_1.16.3-0ubuntu1_amd64.deb)  404  Not Found [IP: 20.106.104.242 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> Error: Process completed with exit code 100.
> ```

Looks like you too forgot to `apt-get update`, the correct version would've been `1.16.3-0ubuntu1.1_i386.deb`.

**Comment by neilyoung** [comment]
Thanks. I added this right now to my workflow script:

```
    steps:
    - name: Update system (Ubuntu)
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
      run: sudo apt update && sudo apt upgrade -y

```

Let's hope :)

**Comment by maciejlibraryx** [comment]
happening now...

**Comment by int-72h** [comment]
I'm also running into this issue now - I don't know if it's an issue with my runner config or a github-wide problem.

**Comment by Cireo** [comment]
Still going on, 4 out of 4 failures since yesterday

**Comment by frenkel** [comment]
Same problem here in the last two days. About 4 out of every 5 builds fail for me due to this.

**Comment by douglas-raillard-arm** [comment]
Same here, lots of jobs failed like this one:
https://github.com/ARM-software/lisa/actions/runs/3884968922/jobs/6628229248

**Comment by traversaro** [comment]
@douglas-raillard-arm @frenkel @Cireo in my experience it is easier to track a problem that appeared again with a new issue, see https://github.com/actions/runner-images/issues/6894 for a new issue tracking this problem.

**Comment by sehz** [comment]
Happening again

**Comment by sh-TU** [comment]
Got the same problem.

**Comment by sehz** [comment]
Tried all the fixes mentioned here and in other sources.  None of that worked

**Comment by sh-TU** [comment]
country mirror worked to me.
https://wiki.ubuntu.com/Mirrors#Country_mirror_requirements

```
sudo sed -i 's/azure\./<country-code>\./' /etc/apt/sources.list
```

**Comment by lhotari** [comment]
Getting "Could not connect to azure.archive.ubuntu.com:80 (52.250.76.244), connection timed out" very frequently with GitHub Actions workflow runs in apache/pulsar .

**Comment by lhotari** [comment]
I first tried apt-spy2 as a workaround since I saw many workarounds in other projects using that. However, it turns out that the solution in apt-spy2 is very poor. When there are a lot of available mirrors, selecting a mirror is slow and there's no ranking of the fastest servers.

In apache/pulsar, I ended up improving https://askubuntu.com/a/719551 solution.

The apache/pulsar PR is https://github.com/apache/pulsar/pull/19225 .

This is the fairly complex shell script that chooses an up-to-date mirror with the fastest download speed.
```bash
function ci_pick_ubuntu_mirror() {
  echo "Choosing fastest up-to-date ubuntu mirror based on download speed..."
  UBUNTU_MIRROR=$({
    # choose mirrors that are up-to-date by checking the Last-Modified header for
    {
      curl -s http://mirrors.ubuntu.com/mirrors.txt
      # also consider Azure's Ubuntu mirror
      echo http://azure.archive.ubuntu.com/ubuntu/
    } | shuf -n 10 \
      | xargs -I {} sh -c 'echo "$(curl -m 5 -sI {}dists/$(lsb_release -c | cut -f2)-security/Contents-$(dpkg --print-architecture).gz|sed s/\\r\$//|grep Last-Modified|awk -F": " "{ print \$2 }" | LANG=C date -f- -u +%s)" "{}"' | sort -rg | awk '{ if (NR==1) TS=$1; if ($1 == TS) print $2 }'
  } | xargs -I {} sh -c 'echo `curl -r 0-102400 -m 5 -s -w %{speed_download} -o /dev/null {}ls-lR.gz` {}' \
    |sort -g -r |head -1| awk '{ print $2  }')
  if [ -z "$UBUNTU_MIRROR" ]; then
      # fallback to full mirrors list
      UBUNTU_MIRROR="mirror://mirrors.ubuntu.com/mirrors.txt"
  fi
  OLD_MIRROR=$(cat /etc/apt/sources.list | grep '^deb ' | head -1 | awk '{ print $2 }')
  echo "Picked '$UBUNTU_MIRROR'. Current mirror is '$OLD_MIRROR'."
  if [[ "$OLD_MIRROR" != "$UBUNTU_MIRROR" ]]; then
    sudo sed -i "s|$OLD_MIRROR|$UBUNTU_MIRROR|g" /etc/apt/sources.list
    sudo apt-get update
  fi
  # set the chosen mirror also in the UBUNTU_MIRROR and UBUNTU_SECURITY_MIRROR environment variables
  # that can be used by docker builds
  echo "UBUNTU_MIRROR=$UBUNTU_MIRROR" >> $GITHUB_ENV
  echo "UBUNTU_SECURITY_MIRROR=$UBUNTU_MIRROR" >> $GITHUB_ENV
}
```

apache/pulsar builds docker images based on ubuntu. In Dockerfiles there's a solution for passing UBUNTU_MIRROR and UBUNTU_SECURITY_MIRROR as environment variables

```Dockerfile
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ARG UBUNTU_MIRROR=mirror://mirrors.ubuntu.com/mirrors.txt
ARG UBUNTU_SECURITY_MIRROR=http://security.ubuntu.com/ubuntu/

# Install some utilities
RUN sed -i -e "s|http://archive\.ubuntu\.com/ubuntu/|${UBUNTU_MIRROR:-mirror://mirrors.ubuntu.com/mirrors.txt}|g" \
     -e "s|http://security\.ubuntu\.com/ubuntu/|${UBUNTU_SECURITY_MIRROR:-http://security.ubuntu.com/ubuntu/}|g" etc/apt/sources.list \
     && echo 'Acquire::http::Timeout "30";\nAcquire::ftp::Timeout "30";\nAcquire::Retries "3";' > /etc/apt/apt.conf.d/99timeout_and_retries \
     && apt-get update \
     && apt-get -y dist-upgrade \
     && apt-get -y install --no-install-recommends netcat dnsutils less procps iputils-ping \
                 python3 python3-kazoo python3-pip \
                 curl ca-certificates wget apt-transport-https
```

I hope this helps others struggling with the same problem.

**Comment by mdrakiburrahman** [comment]
For anyone on this, this was an infrastructure problem with Canonical servers during a maintenance event (they identified the root cause and are applying the fix as we speak) - the Microsoft team opened an incident and are working with Canonical SREs.

FYI - the Azure-hosted mirrors (`azure.archive.ubuntu.com`) are just cache proxies that forward traffic to Canonical servers when there's a cache miss - which is why the thrown messages shows `azure.blah....`. If you took out the `azure.` part with `sed` in `/etc/apt/sources.list` (say, in your Dockerfile), you'd still repro the issue hitting `archive.ubuntu.com`.

(Our own build systems - not on Github - were also suffering, it seems to be coming back now - should be resolved once the Canonical Infra is back up today).

**Comment by traversaro** [comment]
Thanks a lot @mdrakiburrahman !

**Comment by hloeung** [comment]
Thanks @mdrakiburrahman.

**Comment by oscartbeaumont** [comment]
I was still experiencing this today and managed to fix it by adding an `sudo apt-get` before my install command. I assume something is being cached that shouldn't have been. Just adding this incase anyone else runs across it.

**Comment by duckduckgrayduck** [comment]
This is happening again: 
https://github.com/MuckRock/documentcloud-whisper-addon/actions/runs/4079033174/jobs/7029963023
Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/mesa-vdpau-drivers_22.0.5-0ubuntu0.3_amd64.deb  404  Not Found [IP: 52.252.75.106 80]

**Comment by hloeung** [comment]
What @catthehacker said, this is saying `404 Not Found` so missing `apt-get update`.

**Comment by sehz** [comment]
Note that when the azure infrastructure is acting up, none of the suggestions works.  Have to wait for it to be fixed.  Alternatively, there should be a more reliable cache or build internal cache.

**Comment by pavkam** [comment]
Happening for me:
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_22.0.5-0ubuntu0.3_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libgl1-mesa-dev_22.0.5-0ubuntu0.3_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
```

**Comment by kgilmer** [comment]
This issue should be re-opened.

**Comment by hloeung** [comment]
> This issue should be re-opened.

Why should it be re-opened? The two last reports are of a different issue - `404  Not Found` vs. the originally reported `503  Service Unavailable`. Packages are constantly updated, you need to call `apt-get update` to refresh the index and to be able to retrieve the latest version of specific packages.

**Comment by alkino** [comment]
https://github.com/BlueBrain/HighFive/actions/runs/4101893950/jobs/7074439380 here is a refresh and a fail from 10 minutes ago

**Comment by kvnschlndt** [comment]
Same here!

**Comment by gvastakis** [comment]
Same here !

**Comment by kdmgs110** [comment]
Same error reproduced on Github Action.

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.81.0-1ubuntu1.7_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (40.119.46.219), connection timed out
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

**Comment by GAAOPS** [comment]
I have faced the same issue today:
`
After this operation, 59.1 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libgraphicsmagick-q16-3 amd64 1.3.30+hg15796-1+ubuntu18.04.1+deb.sury.org+2 [1181 kB]
Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 graphicsmagick amd64 1.3.30+hg15796-1+ubuntu18.04.1+deb.sury.org+2 [953 kB]
Err:3 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 fonts-droid-fallback all 1:6.0.1r16-1.1
  Connection failed [IP: 51.11.236.225 80]
Err:4 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 poppler-data all 0.4.8-2
  Could not connect to azure.archive.ubuntu.com:80 (51.11.236.225), connection timed out [IP: 51.11.236.225 80]
Err:5 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 fonts-noto-mono all 20171026-2
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Ign:6 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsimage2 amd64 2.2.7-1ubuntu2.9
Err:7 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libijs-0.35 amd64 0.35-13
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Err:8 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libjbig2dec0 amd64 0.13-6
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Ign:9 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9-common all 9.26~dfsg+0-0ubuntu0.18.04.17
Ign:10 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9 amd64 9.26~dfsg+0-0ubuntu0.18.04.17
Ign:11 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 ghostscript amd64 9.26~dfsg+0-0ubuntu0.18.04.17
Ign:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libwebpmux3 amd64 0.6.1-2ubuntu0.18.04.1
Err:13 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.4
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Ign:14 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsfilters1 amd64 1.20.2-0ubuntu3.1
Err:6 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsimage2 amd64 2.2.7-1ubuntu2.9
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Err:9 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9-common all 9.26~dfsg+0-0ubuntu0.18.04.17
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Err:10 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9 amd64 9.26~dfsg+0-0ubuntu0.18.04.17
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Err:11 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 ghostscript amd64 9.26~dfsg+0-0ubuntu0.18.04.17
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Err:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libwebpmux3 amd64 0.6.1-2ubuntu0.18.04.1
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Err:14 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsfilters1 amd64 1.20.2-0ubuntu3.1
  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
Fetched 2134 kB in 1min 46s (20.2 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/f/fonts-android/fonts-droid-fallback_6.0.1r16-1.1_all.deb  Connection failed [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/poppler-data/poppler-data_0.4.8-2_all.deb  Could not connect to azure.archive.ubuntu.com:80 (51.11.236.225), connection timed out [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/f/fonts-noto/fonts-noto-mono_20171026-2_all.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/cups/libcupsimage2_2.2.7-1ubuntu2.9_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/i/ijs/libijs-0.35_0.35-13_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/j/jbig2dec/libjbig2dec0_0.13-6_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9-common_9.26~dfsg+0-0ubuntu0.18.04.17_all.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9_9.26~dfsg+0-0ubuntu0.18.04.17_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript_9.26~dfsg+0-0ubuntu0.18.04.17_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libw/libwebp/libwebpmux3_0.6.1-2ubuntu0.18.04.1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gsfonts/gsfonts_8.11+urwcyr1.0.7~pre44-4.4_all.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/cups-filters/libcupsfilters1_1.20.2-0ubuntu3.1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 51.11.236.225 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

`

**Comment by VeithMetro** [comment]
Try to add these commands before installing any packages, it fixes the issue for me:
`sudo gem install apt-spy2
sudo apt-spy2 check
sudo apt-spy2 fix --commit
sudo apt-get update`

**Comment by D-Simona-G** [comment]
> Same error reproduced on Github Action.
> 
> ```
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.81.0-1ubuntu1.7_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (40.119.46.219), connection timed out
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> Error: Process completed with exit code 100.
> ```

Same problem here

**Comment by ddelange** [comment]
@VeithMetro thanks for the tip!

fwiw, it looks like `sudo apt-spy2 check` is not needed, and `sudo apt-spy2 fix --commit` [works without it](https://github.com/lagged/apt-spy2/blob/v0.7.3/lib/apt/spy2.rb#L19).

to save some minutes (with GitHub-hosted runners being in the United States):
```
sudo gem install apt-spy2
sudo apt-spy2 fix --commit --launchpad --country=US
sudo apt-get update
```

**Comment by Betree** [comment]
We used a different approach to work around this issue:

```yaml
steps:
  - name: Hack sources.list
    run: sudo sed -i 's|http://azure.archive.ubuntu.com/ubuntu/|http://mirror.arizona.edu/ubuntu/|g' /etc/apt/sources.list
  - ...
```

You can pick any mirror from https://launchpad.net/ubuntu/+archivemirrors, ideally one in the US since Github Actions servers are in the US.

**Comment by ddelange** [comment]
hard-coding a specific mirror will most likely overload that particular mirror if too many people pick that particular server. poor universities 😅

**Comment by Spenhouet** [comment]
Adding apt-spy2 did not do the trick for me.
```
The following packages have unmet dependencies:
 libegl-mesa0 : Depends: libgbm1 (= 22.0.5-0ubuntu0.1) but 22.0.5-0ubuntu0.3 is to be installed
                Depends: libglapi-mesa (= 22.0.5-0ubuntu0.1) but 22.0.5-0ubuntu0.3 is to be installed
E: Unable to correct problems, you have held broken packages.
Failed to install browsers
Error: Installation process exited with code: 100
```

**Comment by ddelange** [comment]
switching to launchpad (my snippet above) fixed that one for us ^

**Comment by ClaudiaKolesnikova** [comment]
> Adding apt-spy2 did not do the trick for me.
> 
> ```
> The following packages have unmet dependencies:
>  libegl-mesa0 : Depends: libgbm1 (= 22.0.5-0ubuntu0.1) but 22.0.5-0ubuntu0.3 is to be installed
>                 Depends: libglapi-mesa (= 22.0.5-0ubuntu0.1) but 22.0.5-0ubuntu0.3 is to be installed
> E: Unable to correct problems, you have held broken packages.
> Failed to install browsers
> Error: Installation process exited with code: 100
> ```

hi, I have the same error, did you fix that?

**Comment by Spenhouet** [comment]
> sudo gem install apt-spy2
> sudo apt-spy2 fix --commit --launchpad --country=US
> sudo apt-get update

@ClaudiaKolesnikova Yes, I did this, suggested by @ddelange.

**Comment by aethernet** [comment]
Same issue for me, and simply running an `apt-get update` before installing anything fixed it.

**Comment by hloeung** [comment]
> Same issue for me, and simply running an `apt-get update` before installing anything fixed it.

Not an "issue", it's what you're meant to do.

When images used are built, they're bundled with a package index. Packages are constantly updated with various security fixes and such and thus indexes can be out-of-date. `apt-get update` is required to pull in the latest package indexes.
