### ISSUE TITLE
Announce/Feedback: Removing Windows Server 2016 virtual environment

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#68]
The Windows Server 2016 virtual environment will be removed in January 2020. You will need to update your workflow files to run on `windows-latest` which will run on the Windows Server 2019 environment instead.

Update 12/10: We have moved the deprecation date to January 2020.

**Comment by wipe2238** [comment]
Does that mean Visual Studio 2017 will be added to `windows-latest`?

**Comment by NickCraver** [comment]
The post and tweet mention Windows 2016 **R2** ([post link](https://github.blog/changelog/2019-10-31-github-actions-windows-server-2016-r2-virtual-environment-will-be-removed-on-november-7/), [tweet link](https://twitter.com/GHchangelog/status/1189977225308909568)).

Can we please remove the R2 there to fix the notes? Or I'm very confused...there wasn't a Windows 2016 R2 ever released to the public AFAIK.

**Comment by kaylangan** [comment]
> Does that mean Visual Studio 2017 will be added to `windows-latest`?

That is the plan. We don't yet have a firm ETA, but ideally by end of the year.

> The post and tweet mention Windows 2016 R2

This is how it's been referred to in our documentation: https://help.github.com/en/github/automating-your-workflow-with-github-actions/software-in-virtual-environments-for-github-actions

**Comment by NickCraver** [comment]
@kaylangan I'm not sure what the best way to say this is, but: that OS doesn't exist. It was a bug in the original documentation too then :)

**Comment by kaylangan** [comment]
@NickCraver Fixed now. Thanks! 🙂

**Comment by hugovk** [comment]
📍 Maybe pin this issue for extra visibility?

**Comment by tvatter** [comment]
... wouldn't it make more sense to wait until Visual Studio 2017 is added to `windows-latest` ? Without it (i.e., on the current `windows-latest`), although `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" my_platform` executes without problem, I still get the dreaded `error: Microsoft Visual C++ 14.0 is required` when trying to install a package.

**Comment by alepauly** [comment]
@tvatter @hugovk We're working on adding the ```Microsoft.VisualStudio.Component.VC.140``` [component](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019) to the VS2019 install. It should show up in the environment in the next few weeks.

**Comment by Skycoder42** [comment]
@alepauly Is there an issue for VC.140 (msvc2015) **and** VC.141 (msvc2017) to track when they have been added?

**Comment by LorenzE** [comment]
Are there any news on adding msvc2017 support to windows-latest (windows server 2019)? I am asking because my builds on windows are dependent on pre-built Qt binaries, which ship for <= msvc2017 only. Thx :)

**Comment by alepauly** [comment]
@LorenzE @Skycoder42 - sorry for the silence here so far but we did make some changes to the windows 2019 runner to include msvc140 (vs2015) and a missing component for msvc141 (vs2017). The latest built rolling out right now has those changes but it won't reach your repos probably until Friday this week or Monday. I'll do my best to keep this issue up to date but please don't hesitate to ping me if you have any questions. Thanks!

**Comment by LorenzE** [comment]
@alepauly Thanks for keeping us in the loop!

**Comment by rvanmil** [comment]
We also need Visual Studio 2017 to keep our cordova-windows builds going. For a while it was possible to run vs2017 on the 2019 environment by installing it through the chocolatey `visualstudio2017buildtools` package, but this has stopped working somewhere around december 12th (the installer fails silently).

**Comment by kaylangan** [comment]
@rvanmil can you point me to a build?

**Comment by rvanmil** [comment]
> @rvanmil can you point me to a build?

Over here, but this is a private repo: https://github.com/oliverit/infrax-cordova-app-wfm/commit/8057bd462c963b3e30b1a209327f1f811a9ac177/checks?check_suite_id=372173496

This is the workflow script I'm using:

```
name: Build for Windows

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: windows-2016

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Node.js 8
      uses: actions/setup-node@master
      with:
        node-version: '8.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Import code signing certificate
      shell: powershell
      run: ./build/certificate.ps1

    - name: Add Yarn global bin to path
      shell: bash
      run: echo "::add-path::$(yarn global bin)"

    - name: Install Cordova
      shell: bash
      run: yarn global add cordova@9

    - name: Install dependencies
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      run: yarn install

    - name: Build - TST - Webpack
      shell: bash
      run: yarn build-tst

    - name: Build - TST - Cordova
      shell: bash
      env:
        MSBUILDDIR: '/C/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin'
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      run: >
        export FILENAME_X64=CordovaApp.Windows10_$(node -p "require('./package.json').version").0_x64 &&
        export FILENAME_X86=CordovaApp.Windows10_$(node -p "require('./package.json').version").0_x86 &&
        cordova prepare windows &&
        cordova build windows --release --archs="x86 x64" --bundle --win --buildConfig=build/build-tst.json &&
        mv ./platforms/windows/build/windows/release/x64/win10/Upload/$FILENAME_X64/$FILENAME_X64.appx ./App-x64-TST.appx &&
        mv ./platforms/windows/build/windows/release/x86/win10/Upload/$FILENAME_X86/$FILENAME_X86.appx ./App-x86-TST.appx

    - name: Build - PRD - Webpack
      shell: bash
      run: yarn build-prd

    - name: Build - PRD - Cordova
      shell: bash
      env:
        MSBUILDDIR: '/C/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin'
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      run: >
        export FILENAME_X64=CordovaApp.Windows10_$(node -p "require('./package.json').version").0_x64 &&
        export FILENAME_X86=CordovaApp.Windows10_$(node -p "require('./package.json').version").0_x86 &&
        cordova prepare windows &&
        cordova build windows --release --archs="x86 x64" --bundle --win --buildConfig=build/build-prd.json &&
        mv ./platforms/windows/build/windows/release/x64/win10/Upload/$FILENAME_X64/$FILENAME_X64.appx ./App-x64-PRD.appx &&
        mv ./platforms/windows/build/windows/release/x86/win10/Upload/$FILENAME_X86/$FILENAME_X86.appx ./App-x86-PRD.appx

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          App-x64-TST.appx
          App-x86-TST.appx
          App-x64-PRD.appx
          App-x86-PRD.appx
```

**Comment by rvanmil** [comment]
Let met know if you need an actual build, I'd be happy to setup a public one.

**Comment by kaylangan** [comment]
Unpinning this issue since we've put this on hold. We want to do a few more investigations before removing the Windows Server 2016 environment.

The exit criteria for this are:
- Visual Studio 2017 can be used on the Windows Server 2019 environment (may require an install via chocolatey, may be pre-installed, etc.)

If you are able to, please use the Windows Server 2019 environment. And if you're **not** able to, please let us know why!

**Comment by wipe2238** [comment]
It's sadly not possible to build projects using v140_xp without VS2017
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140_xp\Toolset.targets(36,5): warning MSB8003: Could not find **WindowsSdkDir_71A** variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. 
>
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find **WindowsSDKDir** variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number.
>
>fatal error C1083: Cannot open include file: '**WinSock2.h**': No such file or directory 

Complete log can be found [here](https://github.com/rotators/sfall/runs/389952672#step:6:14); all jobs have [runs-on](https://github.com/rotators/sfall/blob/0dfe14ff4f9b89ff3995f093c01263583c1a67e3/.github/workflows/Build.yml#L12) set to `windows-latest`

**Comment by canihavesomecoffee** [comment]
@wipe2238 If they'd merge my PR for related issue #288 your problems might be over as well.

**Comment by Croydon** [comment]
We do build packages for the C/C++ package manager Conan. We have a huge build matrix, including various builds with VS 2015, 2017 and 2019. We need pre-installed variants for these three. Installing them in every job every time again takes way too much time

**Comment by wipe2238** [comment]
@canihavesomecoffee Oh my, i have just a perfect place for workaround; 14 minutes is nothing for once-per-day schedule job at dead hour. Thanks! :>

**Comment by ruudboon** [comment]
Visual Studio 2017 is currently [needed](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2) to build PHP or PHP extensions. Would be nice if there was a way install 2017 without the need to wait 14 minutes for every build.

**Comment by ruudboon** [comment]
@kaylangan any updates?

**Comment by miketimofeev** [comment]
@alepauly @thejoebourneidentity could you update that announcement, please?

**Comment by mloskot** [comment]
I'm currently evaluating GitHub Actions for several Boost libraries and trying our `b2` build driver with `msvc-14.0`, `msvc-14.1`, `msvc-14.2` of which only the latests succeeds, all on `windows-latest`.

However, https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md lists both:
- Microsoft.VisualStudio.Component.VC.140
- Microsoft.VisualStudio.Component.VC.v141

Is this documentation out of sync with the actual environment on `windows-latest`?
All the `vc140`, `vc141` toolsets available on `windows-latest?

**Comment by al-cheb** [comment]
Hello, @mloskot 
Thank you. I will update documentation for [windows-latest] to support only [msvc-14.2].

**Comment by thejoebourneidentity** [comment]
Hello everyone. We've decided that we're going to hang onto the Windows-2016 environment a bit longer. I'm going to close this issue and will revisit in the future if we feel like the need for this returns. Thank you all for the your feedback.

**Comment by VerdonTrigance** [comment]
> Hello everyone. We've decided that we're going to hang onto the Windows-2016 environment a bit longer. I'm going to close this issue and will revisit in the future if we feel like the need for this returns. Thank you all for the your feedback.

Hey, what is going on?

```
##[error]This job was blocked because it uses the hosted agent vs2015-win2012r2 which was permanently removed on April 2nd, 2020.  See https://aka.ms/blocked-hosted-agent for more information.
,##[error]The remote provider was unable to process the request.
```

Why it has been deleted without providing Sharepoint SDK on a new images?

`##[error]MVideo.Acquiring.SpDAL\Models\SpListItemClaim.cs(1,17): Error CS0234: The type or namespace name 'SharePoint' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)`

**Comment by brandonros** [comment]
if this is removed, https://github.com/actions/virtual-environments/blame/master/README.md#L14 shouldn't it be cleaned up from the README?

**Comment by maxim-lobanov** [comment]
@brandonros , No, WinServer 2016 is still available: https://github.com/actions/virtual-environments/issues/68#issuecomment-602652021
