### ISSUE TITLE
Add rustfmt once again [regression]

### ISSUE THREAD

**Issue by sjackman** [actions/virtual-environments#797]
Today's update to `ubuntu-18.04` appears to have removed `rustfmt`, which was present in previous releases.

**Tool information**
- Tool name: rustfmt
- Tool license: Apache License
- Add or update? Add once again
- Desired version: 1.4.12
- Approximate size: ?
- If this is an add request:
  - Brief description of tool: Format Rust code
  - URL for tool's homepage: https://github.com/rust-lang/rustfmt

**Area for Triage**:

**Question, Bug, or Feature?**:
Regression (Bug / Feature)

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
`rustup component add rustfmt`

**Tool installation time in runtime**
20 seconds

**Are you willing to submit a PR?**
Sure. Could you please point me to the file / location that needs to be modified?

**Comment by miketimofeev** [comment]
Hi @sjackman! There was a rollback and then we deployed new image, could you please check rustfm one more time? Rustfm works for me at the moment
![image](https://user-images.githubusercontent.com/48208649/80564890-c566d680-89f7-11ea-96cc-9adb1f012448.png)

**Comment by sjackman** [comment]
It looks like the current deployment is 4% of the way through. I'm hopeful that will resolve my issue. Thanks, Mike! https://github.com/actions/virtual-environments#available-environments

**Comment by miketimofeev** [comment]
@sjackman is your issue persists? If yes, could you please provide run examples?

**Comment by sjackman** [comment]
Yes, the issue persists.
```console
$ rustfmt --version
error: 'rustfmt' is not installed for the toolchain '1.43.0-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustfmt`
```
It's a private repo `check_run_id=630482101`.

**Comment by miketimofeev** [comment]
@sjackman could you please also provide an image version, which can be found in 'Set up job' stage?
![image](https://user-images.githubusercontent.com/48208649/80699660-0852a800-8ae5-11ea-8459-52c6416bd4ed.png)

**Comment by sjackman** [comment]
```
  Environment: ubuntu-18.04
  Version: 20200406.2
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200406.2/images/linux/Ubuntu1804-README.md
```

```
rust (1.42.0)
cargo (1.42.0)
rustfmt (1.4.11-stable)
```
https://github.com/actions/virtual-environments/blob/ubuntu18/20200406.2/images/linux/Ubuntu1804-README.md

That's the problem. I need to wait for rust 1.43.0 to roll out.

**Comment by miketimofeev** [comment]
@sjackman thanks for the update. Rust 1.43 will be available on the next week's deployment(approx Tuesday or Wednesday if nothing goes wrong)

**Comment by sjackman** [comment]
Thanks for the update, Mikhail. Feel free to close this issue.

**Comment by miketimofeev** [comment]
@sjackman let's leave it till the rollout is finished if you don't mind

**Comment by miketimofeev** [comment]
@sjackman the image has been rolled out.
```
Run rustfmt --version
rustfmt 1.4.12-stable (a828ffe 2020-03-11)
```
I'm going to close the issue, but feel free to ping me if you have any concerns.
Thank you!

**Comment by sjackman** [comment]
Thank you, Mike!
